config/routes.rb
Rails.application.routes.draw do
  root'pages#welcome', as: :welcome
  get'/portfolio'=>'portfolio#portfolio', as: :portfolio
  get'/about'=>'about#about', as: :about
  get 'contact'=>'contact#contact', as: :contact
   get 'blog'=>'blog#blog', as: :blog

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/about/about.html.erb
<div class="main about">
  <div class="container">
    <div class="row">
      <div class="col-md-6 im">
        <img alt="Me" src="https://portfolio-rails-2633.herokuapp.com/assets/me-50056699c4a6e91e21a81298d9954d18.jpg">
      </div>
    <div class="nd">
      <h2>Hello. My name is <span class="highlight">Matt Healy</span></h2>
      <p>I was born in 1975 in London and raised in Newcastle and Northumberland before moving to Macclesfield at 10. Dropped out and worked around from 16 on.</p>
      <p>Since 2001, I've been pursuing my passion, building websites and developing my creativity.</p>
      </div>
    </div>
  </div>
</div>

app/views/blog/blog.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title"></h1>
            <div class="account-wall">
         				<h2>Login</h2>
                <form class="form-signin">
                <input type="text" class="form-control"id="email" placeholder="Email" required autofocus>
                <input type="password" class="form-control" placeholder="Password" required>
                <button class="btn btn-lg btn-primary btn-block" type="button"onclick="check()">Sign in</button>
         
                </form>
            </div>
        </div>
    </div>
</div>

app/views/contact/contact.html.erb
<div class="main ca">
  <div class="conta">
    <h2>Contact Me
    </h2>
    <div class="row">
      <div class="col-md-2"><a class="linkedin" href="#">linkedin</a></div>
      <div class="col-md-2"><a class="github" href="#">github</a></div>
      <div class="col-md-2"><a class="twitter" href="#">twitter</a></div>
      <div class="col-md-2"><a class="facebook" href="#">facebook</a></div>
      <div class="col-md-2"><a class="gplus" href="#">google plus</a></div>
      <div class="col-md-2"><a class="instagram" href="#">instagram</a></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
<div class="banner-header">
  <div class="container">
  	<div class="row">
      <div class="col-md-8 col-sm-9 col-xs-8">
        <ul class="style-ul">
          <li>
            <%= link_to "Welcome", welcome_path() %>
          </li>
          <li>
            <%= link_to "Portfolio", portfolio_path() %>
            
          </li>
          <li>
            <%= link_to "Blog", blog_path() %>
          </li>
          <li>
            <%= link_to "About",about_path() %>
          </li>
          <li>
             <%= link_to "Contact",contact_path() %>
          </li>
        </ul>
      </div>
    <div class="col-md-4 col-sm-3 col-xs-4">
          <h4 class="repair-h4">Thinh Lemo</h4>
    </div>
  	</div>
	</div>
</div>
<%= yield %>
<div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="contact">
           <li>
            <a class="a" href="#">.</a>
          </li>
          <li>
            <a class="b" href="#">.</a>
          </li>
          <li>
            <a class="c" href="#">.</a>
          </li>
        </ul>
        </div>
      </div>
      <div class="one">
   <p class="text-right">© 2015 Thinh Lemo</p>
      </div>
 
	</div>
</div>
  <script>
    function check(){
      var email = document.getElementById('email');
      var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
      	if (!filter.test(email.value)) 
        		{ alert('Email không hợp lệ.\nExample@gmail.com');
           	email.focus; return false;
          	} 
      	else { alert('Ok, Email hợp lệ.');
              window.location="<%=welcome_path() %>";
             }
    }
  </script>

</body>
</html>

app/views/pages/welcome.html.erb
<body>
<div class="bg-main">
<div class="container">
    <div class="row">
     
      <div class="col-md-12 text-right">
          <h2 class="repair-h2">Hello. My name is <span class="hight-light">Thinh Lemo</span> and I<br> have creative ideas and build websites</h2>
          <h2 class="repair-h2"><a href="https://portfolio-rails-2633.herokuapp.com/portfolio#">View my Work</a></h2>
  
      </div>
    </div>
	</div>
</div>


</body>

app/views/portfolio/portfolio.html.erb
<body>
  <div class ="pages">
  <div class="main-home">
     <div class="container">
    </div>
</div>
</div>
   <div class="noi-dung">
    <div class="row"> 
      <a class="col-md-6 project" href="#"> 
        <div class="thumbnail-header"> 
          <div class="thumbnail-header-btn">
          </div>
          <div class="thumbnail-header-btn">
          </div>
          <div class="thumbnail-header-btn">
          </div> 
        </div> 
        <div class="thumbnail">
          <img  src="https://portfolio-rails-2633.herokuapp.com/assets/project01-0ff155425c5a026839c43ae7c5089f1e.jpg">
        </div>
        <h3>TravelGo’s Booking App</h3>
        <p>NGO liberal change-makers global time of extraordinary change, prevention climate change mobilize shift. Communities, social movement United Nations, Oxfam planned giving Global South humanitarian. Maximize.</p>
      </a> 
      <a class="col-md-6 project" href="#">
        <div class="thumbnail-header"> 
          <div class="thumbnail-header-btn">
          </div> 
          <div class="thumbnail-header-btn">
          </div> 
          <div class="thumbnail-header-btn">
          </div> 
        </div>
        <div class="thumbnail">
        <img src="https://portfolio-rails-2633.herokuapp.com/assets/project02-ba5afb4eb817317b6be7ba2948be9fe3.jpg"> 
        </div> <h3>Breather’s Reservation Site</h3> 
        <p>Pursue these aspirations free-speech healthcare sharing economy freedom. Beneficiaries gender rights raise awareness change movements provide. Eradicate, diversification inspire breakthroughs, incubation; solve Peace Corps. Innovate.</p>
      </a> 
    </div> 
    <div class="row"> <a class="col-md-6 project" href="#">
      <div class="thumbnail-header"> <div class="thumbnail-header-btn">
        </div> 
        <div class="thumbnail-header-btn">
        </div>
        <div class="thumbnail-header-btn">
        </div>
      </div>
      <div class="thumbnail">
      <img src="https://portfolio-rails-2633.herokuapp.com/assets/project03-f820dd50db97b4bef375e7645466b30e.jpg">
      </div>
      <h3>EnVogue Events’ Portfolio</h3>
      <p>Informal economies; underprivileged, grantees transformative prosperity. Education best practices connect achieve plumpy'nut. Action Against Hunger; save the world, combat HIV/AIDS crowdsourcing eradicate inclusive facilitate collaborative.</p> 
      </a> 
      <a class="col-md-6 project" href="#">
        <div class="thumbnail-header">
          <div class="thumbnail-header-btn">
          </div>
          <div class="thumbnail-header-btn">
          </div> 
          <div class="thumbnail-header-btn">
          </div>
        </div> 
        <div class="thumbnail"> 
        <img  src="https://portfolio-rails-2633.herokuapp.com/assets/project04-1e66995d7e1fc884b9d84f6d9a2f135a.jpg"> 
        </div> <h3>Gauntlet Gallery</h3>
        <p>Small-scale farmers; collaborative cities Bill and Melinda Gates best practices equity health theory of social change human experience. Tackle rural development relief worldwide respect, economic.</p> 
      </a> </div> <div class="row">
    <a class="col-md-6 project" href="#">
      <div class="thumbnail-header">
        <div class="thumbnail-header-btn">
        </div> 
        <div class="thumbnail-header-btn">
        </div>
        <div class="thumbnail-header-btn">
        </div>
      </div>
      <div class="thumbnail"> 
        <img src="https://portfolio-rails-2633.herokuapp.com/assets/project05-be5f6a9baca0191c49d4b424555f9287.jpg">
      </div>
      <h3>Koi Pond Online Visitors Guide</h3>
      <p>UNICEF, research Ford Foundation outcomes collaborative consumption turmoil change lives. Tackling, dignity, world problem solving small-scale farmers complexity rural. Emergent humanitarian, necessities effect, challenges of.</p>
    </a> 
    <a class="col-md-6 project" href="#">
      <div class="thumbnail-header">
        <div class="thumbnail-header-btn">
        </div>
        <div class="thumbnail-header-btn">
        </div>
        <div class="thumbnail-header-btn">
        </div> 
      </div>
      <div class="thumbnail">
      <img  src="https://portfolio-rails-2633.herokuapp.com/assets/project06-ec513d22a13d9c4c5f959882fa9ea7bb.jpg"> 
      </div>
      <h3>Academy of Sciences  Newsletter</h3>
      <p>Aid collaborative global network overcome injustice honesty measures. Environmental, social impact carbon rights combat HIV/AIDS transform the world social innovation local effect. Free expression committed.</p>
    </a> 
    </div> 
  </div>
</body>